version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    working_directory: /go/src/github.com/MattHodge/terraform-provider-octopusdeploy
    environment:
      # GITHUB_TOKEN: Specified In UI
      # OCTOPUS_APIKEY: Specified In UI
      # OCTOPUS_URL: Specified In UI
      GO111MODULE: on
    steps:
      - checkout
      - run:
          go version
          go test -v -timeout 120s ./octopusdeploy/...
